# Generated by Django 5.2.1 on 2025-06-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WTM_app', '0007_service_servicestep_whychooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='EcoSort Recycling Services', max_length=150)),
                ('hero_subtitle', models.CharField(default='Innovative, Sustainable, Community-Driven', max_length=255)),
                ('hero_desc', models.TextField(default='Discover how EcoSort is transforming waste management and recycling for a cleaner, greener future.')),
                ('cta_text', models.CharField(default='Ready to Make a Difference?', max_length=120)),
                ('cta_btn', models.CharField(default='Join EcoSort Now', max_length=40)),
                ('footer_text', models.CharField(default='© 2025 EcoSort | All rights reserved.', max_length=120)),
            ],
        ),
    ]
