# Generated by Django 5.2.1 on 2025-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WTM_app', '0008_servicepagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Activity', max_length=100)),
                ('subtitle', models.CharField(default='Track your recycling journey and impact.', max_length=200)),
                ('stats_title', models.CharField(default='Your Eco Stats', max_length=100)),
                ('activity_title', models.CharField(default='Recent Activity', max_length=100)),
                ('empty_message', models.CharField(default="You haven't made any pickup requests yet. Start recycling today!", max_length=200)),
                ('cta_request', models.CharField(default='Request a Pickup', max_length=100)),
                ('cta_rewards', models.CharField(default='View My Rewards', max_length=100)),
                ('goal_label', models.CharField(default='Monthly Recycling Goal', max_length=100)),
                ('goal_kg', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text="Font Awesome class, e.g. 'fas fa-recycle'", max_length=100),
        ),
        migrations.AlterField(
            model_name='servicestep',
            name='icon',
            field=models.CharField(help_text='Step number or icon', max_length=100),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='icon',
            field=models.CharField(help_text='Font Awesome class', max_length=100),
        ),
    ]
