# Generated by Django 5.2.1 on 2025-06-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WTM_app', '0009_activitypagecontent_alter_service_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Contact Us', max_length=100)),
                ('hero_subtitle', models.CharField(default='Smart Waste Disposal for a Cleaner Future', max_length=255)),
                ('hero_image', models.ImageField(upload_to='contact_hero/')),
                ('contact_heading', models.CharField(default='We are always ready to help you and answer your questions', max_length=100)),
                ('contact_message', models.TextField(default='Whether you have a question, a suggestion, or just want to say hello...')),
                ('open_days', models.CharField(default='Monday - Friday 08.00 – 18.00', max_length=100)),
                ('address', models.CharField(default='100 S Main St, New York, NY', max_length=255)),
                ('phone', models.CharField(default='+1 123 456 789', max_length=20)),
                ('email', models.EmailField(default='contact@ecosort.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer/')),
                ('about_text', models.TextField()),
                ('company_home', models.URLField(default='#')),
                ('company_services', models.URLField(default='#')),
                ('company_about', models.URLField(default='#')),
                ('company_contact', models.URLField(default='#')),
                ('service1', models.CharField(default='Waste Collection', max_length=100)),
                ('service2', models.CharField(default='Waste Recycling', max_length=100)),
                ('service3', models.CharField(default='Waste to Rewards', max_length=100)),
                ('service4', models.CharField(default='Recycling Education', max_length=100)),
                ('service5', models.CharField(default='EcoSort Support', max_length=100)),
                ('service6', models.CharField(default='Medical Waste', max_length=100)),
                ('newsletter_text', models.CharField(default='Your email is safe with us. We don’t spam.', max_length=255)),
                ('facebook', models.URLField(default='#')),
                ('twitter', models.URLField(default='#')),
                ('linkedin', models.URLField(default='#')),
                ('youtube', models.URLField(default='#')),
                ('whatsapp', models.URLField(default='#')),
            ],
        ),
    ]
