# Generated by Django 5.2.1 on 2025-06-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WTM_app', '0010_contactpage_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='company_about',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='company_contact',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='company_home',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='company_services',
            field=models.URLField(blank=True, null=True),
        ),
    ]
